# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: DeveloperTools
  images: |
    - name: keycloak
      image: docker.io/bitnami/keycloak:26.3.2-debian-12-r2
    - name: keycloak-config-cli
      image: docker.io/bitnami/keycloak-config-cli:6.4.0-debian-12-r11
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 26.3.2
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://578672650824.dkr.ecr.us-east-2.amazonaws.com/bitnami-charts
  version: 15.5.21-arm64
- name: common
  repository: oci://578672650824.dkr.ecr.us-east-2.amazonaws.com/bitnami-charts
  tags:
  - bitnami-common
  version: 2.31.4
description: Keycloak is a high performance Java-based identity and access management
  solution. It lets developers add an authentication layer to their applications with
  minimum effort.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/keycloak/img/keycloak-stack-220x234.png
keywords:
- keycloak
- access-management
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: keycloak
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/keycloak
version: 25.1.0-arm64
